name: 'Prepare Rust toolchain'
description: 'Install the Rust toolchain and set up the cache'

runs:
  using: "composite"
  steps:
    - run: rustup toolchain install stable --profile minimal -c rustfmt -c clippy
      shell: bash
      name: Install the Rust toolchain

    - uses: Swatinem/rust-cache@v2
      name: Use cached dependencies and artifacts

    - uses: arduino/setup-protoc@v2
      name: Install Protoc
